ENVIRONMENT:
  MAX_EPISODE_STEPS: 500
SIMULATOR:
  AGENT_0:
    SENSORS: ['RGB_SENSOR', 'DEPTH_SENSOR']
  HABITAT_SIM_V0:
    GPU_DEVICE_ID: 0
  RGB_SENSOR:
    WIDTH: 256
    HEIGHT: 256
  DEPTH_SENSOR:
    WIDTH: 256
    HEIGHT: 256
TASK:
  TYPE: Nav-v0
  SUCCESS_DISTANCE: 0.2
  SENSORS: ['POINTGOAL_SENSOR']
  POINTGOAL_SENSOR:
    TYPE: PointGoalSensor
    GOAL_FORMAT: POLAR
  MEASUREMENTS: ['SPL']
  SPL:
    TYPE: SPL
    SUCCESS_DISTANCE: 0.2
RECORDER:
  NUM_FOR_REC: 1
  START_EVERY: 1000000000
  VIDEO_LENGTH: 10000
DATASET:
  # TYPE: PointNav-v1
  SPLIT: val_mini
  POINTNAVV1:
    DATA_PATH: /home/titarenkoan/habitat-root/habitat-api/data/datasets/pointnav/gibson/v1/{split}/{split}.json.gz
